//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XIVBackup {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("XIVBackup.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string backup_label_text {
            get {
                return ResourceManager.GetString("backup.label.text", resourceCulture);
            }
        }
        
        internal static string backup_label_title {
            get {
                return ResourceManager.GetString("backup.label.title", resourceCulture);
            }
        }
        
        internal static string info_label {
            get {
                return ResourceManager.GetString("info.label", resourceCulture);
            }
        }
        
        internal static string backup_button_text {
            get {
                return ResourceManager.GetString("backup.button.text", resourceCulture);
            }
        }
        
        internal static string restore_label_title {
            get {
                return ResourceManager.GetString("restore.label.title", resourceCulture);
            }
        }
        
        internal static string restore_label_text {
            get {
                return ResourceManager.GetString("restore.label.text", resourceCulture);
            }
        }
        
        internal static string restore_button_text {
            get {
                return ResourceManager.GetString("restore.button.text", resourceCulture);
            }
        }
        
        internal static string close_button_text {
            get {
                return ResourceManager.GetString("close.button.text", resourceCulture);
            }
        }
        
        internal static string xivbackup_title {
            get {
                return ResourceManager.GetString("xivbackup.title", resourceCulture);
            }
        }
        
        internal static string filter_fcbz {
            get {
                return ResourceManager.GetString("filter.fcbz", resourceCulture);
            }
        }
        
        internal static string filter_all {
            get {
                return ResourceManager.GetString("filter.all", resourceCulture);
            }
        }
        
        internal static string backup_exists_warn {
            get {
                return ResourceManager.GetString("backup.exists.warn", resourceCulture);
            }
        }
        
        internal static string warning_autodetect {
            get {
                return ResourceManager.GetString("warning.autodetect", resourceCulture);
            }
        }
        
        internal static string warning_autodetect_title {
            get {
                return ResourceManager.GetString("warning.autodetect.title", resourceCulture);
            }
        }
        
        internal static string results_backup_success {
            get {
                return ResourceManager.GetString("results.backup.success", resourceCulture);
            }
        }
        
        internal static string results_restore_success {
            get {
                return ResourceManager.GetString("results.restore.success", resourceCulture);
            }
        }
        
        internal static string results_backup_error_read {
            get {
                return ResourceManager.GetString("results.backup.error.read", resourceCulture);
            }
        }
        
        internal static string results_backup_error_write {
            get {
                return ResourceManager.GetString("results.backup.error.write", resourceCulture);
            }
        }
        
        internal static string results_restore_error_read {
            get {
                return ResourceManager.GetString("results.restore.error.read", resourceCulture);
            }
        }
        
        internal static string results_restore_error_write {
            get {
                return ResourceManager.GetString("results.restore.error.write", resourceCulture);
            }
        }
        
        internal static string results_error_default {
            get {
                return ResourceManager.GetString("results.error.default", resourceCulture);
            }
        }
        
        internal static string results_empty {
            get {
                return ResourceManager.GetString("results.empty", resourceCulture);
            }
        }
    }
}
