//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XIVBackup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XIVBackup.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string backup_button_text {
            get {
                return ResourceManager.GetString("backup.button.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists.\nDo you want to replace it?.
        /// </summary>
        internal static string backup_exists_warn {
            get {
                return ResourceManager.GetString("backup.exists.warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup your settings and macros to a compressed file..
        /// </summary>
        internal static string backup_label_text {
            get {
                return ResourceManager.GetString("backup.label.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string backup_label_title {
            get {
                return ResourceManager.GetString("backup.label.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close_button_text {
            get {
                return ResourceManager.GetString("close.button.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any File (*).
        /// </summary>
        internal static string filter_all {
            get {
                return ResourceManager.GetString("filter.all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFXIV Config Backup (*.fcbz).
        /// </summary>
        internal static string filter_fcbz {
            get {
                return ResourceManager.GetString("filter.fcbz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup and restore your hotbars, macros, HUD layout, etc..
        /// </summary>
        internal static string info_label {
            get {
                return ResourceManager.GetString("info.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string restore_button_text {
            get {
                return ResourceManager.GetString("restore.button.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore your backed up settings and macros..
        /// </summary>
        internal static string restore_label_text {
            get {
                return ResourceManager.GetString("restore.label.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string restore_label_title {
            get {
                return ResourceManager.GetString("restore.label.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read settings at:\n{0}.
        /// </summary>
        internal static string results_backup_error_read {
            get {
                return ResourceManager.GetString("results.backup.error.read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not write backup at:\n{0}.
        /// </summary>
        internal static string results_backup_error_write {
            get {
                return ResourceManager.GetString("results.backup.error.write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup successful!\n{0}.
        /// </summary>
        internal static string results_backup_success {
            get {
                return ResourceManager.GetString("results.backup.success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These results are empty and should never show up.\nIf it does...uh...hi there! o/.
        /// </summary>
        internal static string results_empty {
            get {
                return ResourceManager.GetString("results.empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This error SHOULD be impossible.\nPlease report this issue at:\nhttps://github.com/Lomeli12/XIVBackup/issues\nResults: {0}.
        /// </summary>
        internal static string results_error_default {
            get {
                return ResourceManager.GetString("results.error.default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read backup file:\n{0}.
        /// </summary>
        internal static string results_restore_error_read {
            get {
                return ResourceManager.GetString("results.restore.error.read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not restore settings to folder:\n{0}.
        /// </summary>
        internal static string results_restore_error_write {
            get {
                return ResourceManager.GetString("results.restore.error.write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully restored backup!\n{0}.
        /// </summary>
        internal static string results_restore_success {
            get {
                return ResourceManager.GetString("results.restore.success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XIVBackup could not auto-detect your game settings folder. The best way to fix this is to place XIVBackup inside your settings folder (where FFXIV.cfg and MACROSYS.dat are located)..
        /// </summary>
        internal static string warning_autodetect {
            get {
                return ResourceManager.GetString("warning.autodetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Folder Not Found.
        /// </summary>
        internal static string warning_autodetect_title {
            get {
                return ResourceManager.GetString("warning.autodetect.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XIVBackup.
        /// </summary>
        internal static string xivbackup_title {
            get {
                return ResourceManager.GetString("xivbackup.title", resourceCulture);
            }
        }
    }
}
